use super::*;
use crate::handlers::*;
use crate::workspace_runtime::*;

pub fn build_router(state: ServerState) -> Router {
    let cors_layer = build_cors_layer(&state.transport_security);

    Router::new()
        .route("/health", get(healthcheck))
        .route("/api/v1/host/bootstrap", get(host_bootstrap))
        .route("/api/v1/host/health", get(host_healthcheck))
        .route(
            "/api/v1/host/preferences",
            get(load_host_preferences_route).put(save_host_preferences_route),
        )
        .route(
            "/api/v1/host/update-status",
            get(get_host_update_status_route),
        )
        .route("/api/v1/host/update-check", post(check_host_update_route))
        .route(
            "/api/v1/host/update-download",
            post(download_host_update_route),
        )
        .route(
            "/api/v1/host/update-install",
            post(install_host_update_route),
        )
        .route(
            "/api/v1/host/workspace-connections",
            get(list_host_workspace_connections_route).post(create_host_workspace_connection_route),
        )
        .route(
            "/api/v1/host/workspace-connections/:connection_id",
            delete(delete_host_workspace_connection_route),
        )
        .route(
            "/api/v1/host/notifications",
            get(list_host_notifications_route).post(create_host_notification_route),
        )
        .route(
            "/api/v1/host/notifications/:notification_id/read",
            post(mark_host_notification_read_route),
        )
        .route(
            "/api/v1/host/notifications/read-all",
            post(mark_all_host_notifications_read_route),
        )
        .route(
            "/api/v1/host/notifications/:notification_id/dismiss-toast",
            post(dismiss_host_notification_toast_route),
        )
        .route(
            "/api/v1/host/notifications/unread-summary",
            get(get_host_notification_unread_summary_route),
        )
        .route("/api/v1/system/health", get(healthcheck))
        .route("/api/v1/system/bootstrap", get(system_bootstrap))
        .route("/api/v1/system/auth/status", get(system_auth_status))
        .route("/api/v1/system/auth/login", post(system_auth_login))
        .route(
            "/api/v1/system/auth/bootstrap-admin",
            post(system_auth_bootstrap_admin),
        )
        .route("/api/v1/system/auth/session", get(system_auth_session))
        .route(
            "/api/v1/access/authorization/current",
            get(current_authorization),
        )
        .route("/api/v1/access/sessions", get(list_access_sessions))
        .route("/api/v1/access/audit", get(list_access_audit))
        .route(
            "/api/v1/access/sessions/current/revoke",
            post(revoke_current_access_session),
        )
        .route(
            "/api/v1/access/sessions/:session_id/revoke",
            post(revoke_access_session),
        )
        .route(
            "/api/v1/access/users/:user_id/sessions/revoke",
            post(revoke_access_user_sessions),
        )
        .route(
            "/api/v1/access/users",
            get(list_access_users).post(create_access_user),
        )
        .route(
            "/api/v1/access/users/:user_id",
            put(update_access_user).delete(delete_access_user),
        )
        .route(
            "/api/v1/access/org/units",
            get(list_access_org_units).post(create_access_org_unit),
        )
        .route(
            "/api/v1/access/org/units/:org_unit_id",
            put(update_access_org_unit).delete(delete_access_org_unit),
        )
        .route(
            "/api/v1/access/org/positions",
            get(list_access_positions).post(create_access_position),
        )
        .route(
            "/api/v1/access/org/positions/:position_id",
            put(update_access_position).delete(delete_access_position),
        )
        .route(
            "/api/v1/access/org/groups",
            get(list_access_user_groups).post(create_access_user_group),
        )
        .route(
            "/api/v1/access/org/groups/:group_id",
            put(update_access_user_group).delete(delete_access_user_group),
        )
        .route(
            "/api/v1/access/org/assignments",
            get(list_access_user_org_assignments).post(upsert_access_user_org_assignment),
        )
        .route(
            "/api/v1/access/org/assignments/:user_id/:org_unit_id",
            delete(delete_access_user_org_assignment),
        )
        .route(
            "/api/v1/access/roles",
            get(list_access_roles).post(create_access_role),
        )
        .route(
            "/api/v1/access/roles/:role_id",
            put(update_access_role).delete(delete_access_role),
        )
        .route(
            "/api/v1/access/policies/permission-definitions",
            get(list_access_permission_definitions),
        )
        .route(
            "/api/v1/access/policies/role-bindings",
            get(list_access_role_bindings).post(create_access_role_binding),
        )
        .route(
            "/api/v1/access/policies/role-bindings/:binding_id",
            put(update_access_role_binding).delete(delete_access_role_binding),
        )
        .route(
            "/api/v1/access/policies/data-policies",
            get(list_access_data_policies).post(create_access_data_policy),
        )
        .route(
            "/api/v1/access/policies/data-policies/:policy_id",
            put(update_access_data_policy).delete(delete_access_data_policy),
        )
        .route(
            "/api/v1/access/policies/resource-policies",
            get(list_access_resource_policies).post(create_access_resource_policy),
        )
        .route(
            "/api/v1/access/policies/resource-policies/:policy_id",
            put(update_access_resource_policy).delete(delete_access_resource_policy),
        )
        .route(
            "/api/v1/access/menus/definitions",
            get(list_access_menu_definitions),
        )
        .route(
            "/api/v1/access/menus/features",
            get(list_access_feature_definitions),
        )
        .route(
            "/api/v1/access/menus/gates",
            get(list_access_menu_gate_results),
        )
        .route(
            "/api/v1/access/menus/policies",
            get(list_access_menu_policies).post(create_access_menu_policy),
        )
        .route(
            "/api/v1/access/menus/policies/:menu_id",
            put(update_access_menu_policy).delete(delete_access_menu_policy),
        )
        .route(
            "/api/v1/access/protected-resources",
            get(list_access_protected_resources),
        )
        .route(
            "/api/v1/access/protected-resources/:resource_type/:resource_id",
            put(upsert_access_protected_resource),
        )
        .route("/api/v1/apps", get(list_apps).post(register_app))
        .route("/api/v1/workspace", get(workspace))
        .route("/api/v1/workspace/overview", get(workspace_overview))
        .route(
            "/api/v1/workspace/resources",
            get(workspace_resources).post(create_workspace_resource),
        )
        .route(
            "/api/v1/workspace/resources/import",
            post(import_workspace_resource),
        )
        .route(
            "/api/v1/workspace/resources/:resource_id",
            patch(update_workspace_resource).delete(delete_workspace_resource),
        )
        .route(
            "/api/v1/workspace/filesystem/directories",
            get(list_workspace_filesystem_directories),
        )
        .route("/api/v1/resources/:resource_id", get(get_resource_detail))
        .route(
            "/api/v1/resources/:resource_id/content",
            get(get_resource_content),
        )
        .route(
            "/api/v1/resources/:resource_id/children",
            get(list_resource_children),
        )
        .route(
            "/api/v1/resources/:resource_id/promote",
            post(promote_resource),
        )
        .route("/api/v1/workspace/knowledge", get(workspace_knowledge))
        .route("/api/v1/workspace/pet", get(workspace_pet_snapshot))
        .route(
            "/api/v1/workspace/pet/dashboard",
            get(workspace_pet_dashboard),
        )
        .route(
            "/api/v1/workspace/pet/presence",
            patch(save_workspace_pet_presence),
        )
        .route(
            "/api/v1/workspace/pet/conversation",
            put(bind_workspace_pet_conversation),
        )
        .route(
            "/api/v1/workspace/agents",
            get(list_agents).post(create_agent),
        )
        .route(
            "/api/v1/workspace/agents/import-preview",
            post(preview_import_agent_bundle_route),
        )
        .route(
            "/api/v1/workspace/agents/import",
            post(import_agent_bundle_route),
        )
        .route(
            "/api/v1/workspace/agents/export",
            post(export_agent_bundle_route),
        )
        .route(
            "/api/v1/workspace/agents/:agent_id",
            patch(update_agent).delete(delete_agent),
        )
        .route(
            "/api/v1/workspace/agents/:agent_id/copy-to-workspace",
            post(copy_workspace_agent_from_builtin_route),
        )
        .route("/api/v1/workspace/teams", get(list_teams).post(create_team))
        .route(
            "/api/v1/workspace/teams/:team_id",
            patch(update_team).delete(delete_team),
        )
        .route(
            "/api/v1/workspace/teams/:team_id/copy-to-workspace",
            post(copy_workspace_team_from_builtin_route),
        )
        .route(
            "/api/v1/workspace/catalog/models",
            get(workspace_catalog_models),
        )
        .route(
            "/api/v1/workspace/catalog/provider-credentials",
            get(workspace_provider_credentials),
        )
        .route(
            "/api/v1/workspace/catalog/management-projection",
            get(workspace_capability_management_projection),
        )
        .route(
            "/api/v1/workspace/catalog/management-projection/disable",
            patch(workspace_capability_asset_disable),
        )
        .route(
            "/api/v1/workspace/catalog/skills",
            post(create_workspace_skill_route),
        )
        .route(
            "/api/v1/workspace/catalog/skills/:skill_id",
            get(get_workspace_skill_route)
                .patch(update_workspace_skill_route)
                .delete(delete_workspace_skill_route),
        )
        .route(
            "/api/v1/workspace/catalog/skills/import-archive",
            post(import_workspace_skill_archive_route),
        )
        .route(
            "/api/v1/workspace/catalog/skills/import-folder",
            post(import_workspace_skill_folder_route),
        )
        .route(
            "/api/v1/workspace/catalog/skills/:skill_id/tree",
            get(get_workspace_skill_tree_route),
        )
        .route(
            "/api/v1/workspace/catalog/skills/:skill_id/files/*relative_path",
            get(get_workspace_skill_file_route).patch(update_workspace_skill_file_route),
        )
        .route(
            "/api/v1/workspace/catalog/skills/:skill_id/copy-to-managed",
            post(copy_workspace_skill_to_managed_route),
        )
        .route(
            "/api/v1/workspace/catalog/mcp-servers",
            post(create_workspace_mcp_server_route),
        )
        .route(
            "/api/v1/workspace/catalog/mcp-servers/:server_name",
            get(get_workspace_mcp_server_route)
                .patch(update_workspace_mcp_server_route)
                .delete(delete_workspace_mcp_server_route),
        )
        .route(
            "/api/v1/workspace/catalog/mcp-servers/:server_name/copy-to-managed",
            post(copy_workspace_mcp_server_to_managed_route),
        )
        .route(
            "/api/v1/workspace/catalog/tools",
            get(list_tools).post(create_tool),
        )
        .route(
            "/api/v1/workspace/catalog/tools/:tool_id",
            patch(update_tool).delete(delete_tool),
        )
        .route(
            "/api/v1/workspace/automations",
            get(list_automations).post(create_automation),
        )
        .route(
            "/api/v1/workspace/automations/:automation_id",
            patch(update_automation).delete(delete_automation),
        )
        .route(
            "/api/v1/workspace/personal-center/profile/runtime-config",
            get(get_user_runtime_config_route).patch(save_user_runtime_config_route),
        )
        .route(
            "/api/v1/workspace/personal-center/profile/runtime-config/validate",
            post(validate_user_runtime_config_route),
        )
        .route(
            "/api/v1/workspace/personal-center/profile",
            patch(update_current_user_profile_route),
        )
        .route(
            "/api/v1/workspace/personal-center/profile/password",
            post(change_current_user_password_route),
        )
        .route("/api/v1/projects", get(projects).post(create_project))
        .route("/api/v1/projects/:project_id", patch(update_project))
        .route(
            "/api/v1/projects/:project_id/promotion-requests",
            get(list_project_promotion_requests).post(create_project_promotion_request),
        )
        .route(
            "/api/v1/projects/:project_id/dashboard",
            get(project_dashboard),
        )
        .route(
            "/api/v1/projects/:project_id/runtime-config",
            get(get_project_runtime_config_route).patch(save_project_runtime_config_route),
        )
        .route(
            "/api/v1/projects/:project_id/runtime-config/validate",
            post(validate_project_runtime_config_route),
        )
        .route(
            "/api/v1/projects/:project_id/resources",
            get(project_resources).post(create_project_resource),
        )
        .route(
            "/api/v1/projects/:project_id/resources/import",
            post(import_project_resource),
        )
        .route(
            "/api/v1/projects/:project_id/resources/folder",
            post(create_project_resource_folder),
        )
        .route(
            "/api/v1/projects/:project_id/resources/:resource_id",
            patch(update_project_resource).delete(delete_project_resource),
        )
        .route(
            "/api/v1/projects/:project_id/knowledge",
            get(project_knowledge),
        )
        .route(
            "/api/v1/projects/:project_id/pet",
            get(project_pet_snapshot),
        )
        .route(
            "/api/v1/projects/:project_id/pet/presence",
            patch(save_project_pet_presence),
        )
        .route(
            "/api/v1/projects/:project_id/pet/conversation",
            put(bind_project_pet_conversation),
        )
        .route(
            "/api/v1/projects/:project_id/agent-links",
            get(list_project_agent_links).post(link_project_agent),
        )
        .route(
            "/api/v1/projects/:project_id/agents/import-preview",
            post(preview_import_project_agent_bundle_route),
        )
        .route(
            "/api/v1/projects/:project_id/agents/import",
            post(import_project_agent_bundle_route),
        )
        .route(
            "/api/v1/projects/:project_id/agents/export",
            post(export_project_agent_bundle_route),
        )
        .route(
            "/api/v1/projects/:project_id/agents/:agent_id/copy-to-project",
            post(copy_project_agent_from_builtin_route),
        )
        .route(
            "/api/v1/projects/:project_id/agent-links/:agent_id",
            delete(unlink_project_agent),
        )
        .route(
            "/api/v1/projects/:project_id/team-links",
            get(list_project_team_links).post(link_project_team),
        )
        .route(
            "/api/v1/projects/:project_id/teams/:team_id/copy-to-project",
            post(copy_project_team_from_builtin_route),
        )
        .route(
            "/api/v1/projects/:project_id/team-links/:team_id",
            delete(unlink_project_team),
        )
        .route("/api/v1/inbox", get(inbox))
        .route("/api/v1/artifacts", get(artifacts))
        .route("/api/v1/knowledge", get(knowledge))
        .route(
            "/api/v1/workspace/promotion-requests",
            get(list_workspace_promotion_requests),
        )
        .route(
            "/api/v1/workspace/promotion-requests/:request_id/review",
            post(review_project_promotion_request),
        )
        .nest("/api/v1/runtime", runtime_routes())
        .layer(cors_layer)
        .with_state(state)
}

pub(crate) fn runtime_routes() -> Router<ServerState> {
    Router::new()
        .route("/bootstrap", get(runtime_bootstrap))
        .route("/config", get(get_runtime_config))
        .route("/config/validate", post(validate_runtime_config_route))
        .route(
            "/config/configured-models/probe",
            post(probe_runtime_configured_model_route),
        )
        .route("/config/scopes/:scope", patch(save_runtime_config_route))
        .route(
            "/sessions",
            get(list_runtime_sessions).post(create_runtime_session),
        )
        .route(
            "/sessions/:session_id",
            get(get_runtime_session).delete(delete_runtime_session),
        )
        .route("/sessions/:session_id/turns", post(submit_runtime_turn))
        .route(
            "/sessions/:session_id/approvals/:approval_id",
            post(resolve_runtime_approval),
        )
        .route(
            "/sessions/:session_id/auth-challenges/:challenge_id",
            post(resolve_runtime_auth_challenge),
        )
        .route(
            "/sessions/:session_id/subruns/:subrun_id/cancel",
            post(cancel_runtime_subrun),
        )
        .route(
            "/sessions/:session_id/memory-proposals/:proposal_id",
            post(resolve_runtime_memory_proposal),
        )
        .route("/sessions/:session_id/events", get(runtime_events))
}
