export {
  bootstrapShellHost,
  checkHostUpdate,
  downloadHostUpdate,
  getHostState,
  getHostUpdateStatus,
  healthcheck,
  installHostUpdate,
  hostClient,
  loadPreferences,
  pickAvatarImage,
  pickAgentBundleArchive,
  pickAgentBundleFolder,
  pickSkillArchive,
  pickSkillFolder,
  restartDesktopBackend,
  saveAgentBundleExport,
  savePreferences,
  listWorkspaceConnections,
  createWorkspaceConnection,
  deleteWorkspaceConnection,
  listNotifications,
  createNotification,
  markNotificationRead,
  markAllNotificationsRead,
  dismissNotificationToast,
  getNotificationUnreadSummary,
  subscribeToNotifications,
} from './shell'

export {
  createIdempotencyKey,
  createWorkspaceClient,
} from './workspace-client'
