export {
  WORKSPACE_AUTH_FAILURE_EVENT,
  WorkspaceApiError,
  decodeApiError,
  isWorkspaceApiError,
  type WorkspaceAuthFailureCode,
  type WorkspaceAuthFailureDetail,
} from './error_mapping'
export {
  createHostHeaders,
  createWorkspaceHeaders,
  fetchBackend,
  fetchHostApi,
  fetchHostOpenApi,
  fetchWorkspaceApi,
  fetchWorkspaceOpenApi,
  normalizeComparableApiPath,
  openWorkspaceOpenApiStream,
  type OpenApiMethod,
  type OpenApiPath,
  type OpenApiPathParams,
  type OpenApiRequestOptions,
  type OpenApiResponse,
  type WorkspaceOpenApiRequestOptions,
  type WorkspaceRequestOptions,
} from './openapi_transport'
export {
  clearStoredWorkspaceSession,
  createRequestId,
  isTauriRuntime,
  joinBaseUrl,
  loadStoredWorkspaceSessions,
  resolveBrowserHostApiBaseUrl,
  resolveBrowserHostAuthToken,
  resolveHostRuntime,
  saveStoredWorkspaceSession,
  type HostRuntimeMode,
} from './workspace_session'
