import type {
  CreateRuntimeSessionInput as OpenApiCreateRuntimeSessionInput,
  ProviderConfig as OpenApiProviderConfig,
  ResolvedExecutionTarget as OpenApiResolvedExecutionTarget,
  ResolveRuntimeApprovalInput as OpenApiResolveRuntimeApprovalInput,
  ResolveRuntimeAuthChallengeInput as OpenApiResolveRuntimeAuthChallengeInput,
  RuntimeApprovalRequest as OpenApiRuntimeApprovalRequest,
  RuntimeAuthChallengeSummary as OpenApiRuntimeAuthChallengeSummary,
  RuntimeAuthStateSummary as OpenApiRuntimeAuthStateSummary,
  RuntimeBootstrap as OpenApiRuntimeBootstrap,
  RuntimeEventEnvelope as OpenApiRuntimeEventEnvelope,
  RuntimeHandoffSummary as OpenApiRuntimeHandoffSummary,
  RuntimeMediationOutcome as OpenApiRuntimeMediationOutcome,
  RuntimeMailboxSummary as OpenApiRuntimeMailboxSummary,
  RuntimeMessage as OpenApiRuntimeMessage,
  RuntimePolicyDecisionSummary as OpenApiRuntimePolicyDecisionSummary,
  RuntimeBackgroundRunSummary as OpenApiRuntimeBackgroundRunSummary,
  RuntimeRunCheckpoint as OpenApiRuntimeRunCheckpoint,
  RuntimeRunKind as OpenApiRuntimeRunKind,
  RuntimeRunSnapshot as OpenApiRuntimeRunSnapshot,
  RuntimeSessionDetail as OpenApiRuntimeSessionDetail,
  RuntimeSessionKind as OpenApiRuntimeSessionKind,
  RuntimeSessionSummary as OpenApiRuntimeSessionSummary,
  RuntimeSubrunSummary as OpenApiRuntimeSubrunSummary,
  RuntimeTraceContext as OpenApiRuntimeTraceContext,
  RuntimeTraceItem as OpenApiRuntimeTraceItem,
  RuntimeWorkerDispatchSummary as OpenApiRuntimeWorkerDispatchSummary,
  RuntimeWorkflowRunDetail as OpenApiRuntimeWorkflowRunDetail,
  RuntimeWorkflowSummary as OpenApiRuntimeWorkflowSummary,
  SubmitRuntimeTurnInput as OpenApiSubmitRuntimeTurnInput,
} from './generated'

export type ResolvedExecutionTarget = OpenApiResolvedExecutionTarget
export type RuntimeSessionKind = OpenApiRuntimeSessionKind
export type RuntimeSessionSummary = OpenApiRuntimeSessionSummary
export type RuntimeRunSnapshot = OpenApiRuntimeRunSnapshot
export type RuntimeRunKind = OpenApiRuntimeRunKind
export type RuntimeMessage = OpenApiRuntimeMessage
export type RuntimeTraceItem = OpenApiRuntimeTraceItem
export type RuntimeTraceContext = OpenApiRuntimeTraceContext
export type RuntimeApprovalRequest = OpenApiRuntimeApprovalRequest
export type RuntimeAuthChallengeSummary = OpenApiRuntimeAuthChallengeSummary
export type RuntimeAuthStateSummary = OpenApiRuntimeAuthStateSummary
export type RuntimeMediationOutcome = OpenApiRuntimeMediationOutcome
export type RuntimePolicyDecisionSummary = OpenApiRuntimePolicyDecisionSummary
export type RuntimeRunCheckpoint = OpenApiRuntimeRunCheckpoint
export type RuntimeEventEnvelope = OpenApiRuntimeEventEnvelope
export type RuntimeSessionDetail = OpenApiRuntimeSessionDetail
export type RuntimeSubrunSummary = OpenApiRuntimeSubrunSummary
export type RuntimeMailboxSummary = OpenApiRuntimeMailboxSummary
export type RuntimeHandoffSummary = OpenApiRuntimeHandoffSummary
export type RuntimeWorkflowSummary = OpenApiRuntimeWorkflowSummary
export type RuntimeWorkflowRunDetail = OpenApiRuntimeWorkflowRunDetail
export type RuntimeBackgroundRunSummary = OpenApiRuntimeBackgroundRunSummary
export type RuntimeWorkerDispatchSummary = OpenApiRuntimeWorkerDispatchSummary
export type ProviderConfig = OpenApiProviderConfig
export type RuntimeBootstrap = OpenApiRuntimeBootstrap
export type CreateRuntimeSessionInput = OpenApiCreateRuntimeSessionInput
export type SubmitRuntimeTurnInput = OpenApiSubmitRuntimeTurnInput
export type ResolveRuntimeApprovalInput = OpenApiResolveRuntimeApprovalInput
export type ResolveRuntimeAuthChallengeInput = OpenApiResolveRuntimeAuthChallengeInput
