use super::*;

pub(super) fn default_permission_definitions() -> Vec<PermissionDefinition> {
    vec![
        PermissionDefinition {
            code: "workspace.overview.read".into(),
            name: "Workspace Overview Read".into(),
            description: "Read the enterprise workspace overview snapshot.".into(),
            category: "workspace".into(),
            resource_type: "workspace".into(),
            actions: vec!["read".into()],
        },
        PermissionDefinition {
            code: "project.view".into(),
            name: "Project View".into(),
            description: "View enterprise project records and dashboards.".into(),
            category: "workspace".into(),
            resource_type: "project".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "project.manage".into(),
            name: "Project Manage".into(),
            description: "Create and update enterprise projects.".into(),
            category: "workspace".into(),
            resource_type: "project".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "task.view".into(),
            name: "Task View".into(),
            description: "View project tasks and their execution history.".into(),
            category: "resource".into(),
            resource_type: "task".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "task.manage".into(),
            name: "Task Manage".into(),
            description: "Create and update project task definitions.".into(),
            category: "resource".into(),
            resource_type: "task".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "task.run".into(),
            name: "Task Run".into(),
            description: "Launch and rerun project tasks through the runtime.".into(),
            category: "resource".into(),
            resource_type: "task".into(),
            actions: vec!["run".into()],
        },
        PermissionDefinition {
            code: "task.intervene".into(),
            name: "Task Intervene".into(),
            description: "Intervene in active project task execution.".into(),
            category: "resource".into(),
            resource_type: "task".into(),
            actions: vec!["intervene".into()],
        },
        PermissionDefinition {
            code: "team.view".into(),
            name: "Team View".into(),
            description: "View enterprise teams and project links.".into(),
            category: "resource".into(),
            resource_type: "team".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "team.manage".into(),
            name: "Team Manage".into(),
            description: "Create, update, and delete enterprise teams.".into(),
            category: "resource".into(),
            resource_type: "team".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "team.import".into(),
            name: "Team Import".into(),
            description: "Copy and import enterprise teams across scopes.".into(),
            category: "resource".into(),
            resource_type: "team".into(),
            actions: vec!["import".into()],
        },
        PermissionDefinition {
            code: "access.users.read".into(),
            name: "Access Users Read".into(),
            description: "Read enterprise users and their access assignments.".into(),
            category: "access-control".into(),
            resource_type: "access.users".into(),
            actions: vec!["read".into()],
        },
        PermissionDefinition {
            code: "access.users.manage".into(),
            name: "Access Users Manage".into(),
            description: "Manage enterprise users and credentials.".into(),
            category: "access-control".into(),
            resource_type: "access.users".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "access.org.read".into(),
            name: "Access Org Read".into(),
            description: "Read organization units, positions, groups, and assignments.".into(),
            category: "access-control".into(),
            resource_type: "access.org".into(),
            actions: vec!["read".into()],
        },
        PermissionDefinition {
            code: "access.org.manage".into(),
            name: "Access Org Manage".into(),
            description: "Manage organization units, positions, groups, and assignments.".into(),
            category: "access-control".into(),
            resource_type: "access.org".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "access.roles.read".into(),
            name: "Access Roles Read".into(),
            description: "Read roles and capability bundles.".into(),
            category: "access-control".into(),
            resource_type: "access.roles".into(),
            actions: vec!["read".into()],
        },
        PermissionDefinition {
            code: "access.roles.manage".into(),
            name: "Access Roles Manage".into(),
            description: "Manage roles and their capability bundles.".into(),
            category: "access-control".into(),
            resource_type: "access.roles".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "access.policies.read".into(),
            name: "Access Policies Read".into(),
            description:
                "Read permission definitions, role bindings, data policies, and resource policies."
                    .into(),
            category: "access-control".into(),
            resource_type: "access.policies".into(),
            actions: vec!["read".into()],
        },
        PermissionDefinition {
            code: "access.policies.manage".into(),
            name: "Access Policies Manage".into(),
            description: "Manage role bindings, data policies, and resource policies.".into(),
            category: "access-control".into(),
            resource_type: "access.policies".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "access.menus.read".into(),
            name: "Access Menus Read".into(),
            description: "Read menu definitions, menu policies, and feature gates.".into(),
            category: "access-control".into(),
            resource_type: "access.menus".into(),
            actions: vec!["read".into()],
        },
        PermissionDefinition {
            code: "access.menus.manage".into(),
            name: "Access Menus Manage".into(),
            description: "Manage menu policies and access-control navigation visibility.".into(),
            category: "access-control".into(),
            resource_type: "access.menus".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "access.sessions.read".into(),
            name: "Access Sessions Read".into(),
            description: "Read enterprise login sessions.".into(),
            category: "access-control".into(),
            resource_type: "access.sessions".into(),
            actions: vec!["read".into()],
        },
        PermissionDefinition {
            code: "access.sessions.manage".into(),
            name: "Access Sessions Manage".into(),
            description: "Revoke enterprise login sessions.".into(),
            category: "access-control".into(),
            resource_type: "access.sessions".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "agent.view".into(),
            name: "Agent View".into(),
            description: "View enterprise agents.".into(),
            category: "resource".into(),
            resource_type: "agent".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "agent.run".into(),
            name: "Agent Run".into(),
            description: "Run enterprise agents.".into(),
            category: "resource".into(),
            resource_type: "agent".into(),
            actions: vec!["run".into()],
        },
        PermissionDefinition {
            code: "agent.debug".into(),
            name: "Agent Debug".into(),
            description: "Debug enterprise agents.".into(),
            category: "resource".into(),
            resource_type: "agent".into(),
            actions: vec!["debug".into()],
        },
        PermissionDefinition {
            code: "agent.edit".into(),
            name: "Agent Edit".into(),
            description: "Create and update enterprise agents.".into(),
            category: "resource".into(),
            resource_type: "agent".into(),
            actions: vec!["edit".into()],
        },
        PermissionDefinition {
            code: "agent.publish".into(),
            name: "Agent Publish".into(),
            description: "Publish enterprise agents.".into(),
            category: "resource".into(),
            resource_type: "agent".into(),
            actions: vec!["publish".into()],
        },
        PermissionDefinition {
            code: "agent.delete".into(),
            name: "Agent Delete".into(),
            description: "Delete enterprise agents.".into(),
            category: "resource".into(),
            resource_type: "agent".into(),
            actions: vec!["delete".into()],
        },
        PermissionDefinition {
            code: "agent.grant".into(),
            name: "Agent Grant".into(),
            description: "Manage enterprise agent authorization.".into(),
            category: "resource".into(),
            resource_type: "agent".into(),
            actions: vec!["grant".into()],
        },
        PermissionDefinition {
            code: "agent.import".into(),
            name: "Agent Import".into(),
            description: "Import and copy enterprise agents across scopes.".into(),
            category: "resource".into(),
            resource_type: "agent".into(),
            actions: vec!["import".into()],
        },
        PermissionDefinition {
            code: "agent.export".into(),
            name: "Agent Export".into(),
            description: "Export enterprise agent bundles.".into(),
            category: "resource".into(),
            resource_type: "agent".into(),
            actions: vec!["export".into()],
        },
        PermissionDefinition {
            code: "resource.view".into(),
            name: "Resource View".into(),
            description: "View protected resources.".into(),
            category: "resource".into(),
            resource_type: "resource".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "resource.upload".into(),
            name: "Resource Upload".into(),
            description: "Upload workspace resources.".into(),
            category: "resource".into(),
            resource_type: "resource".into(),
            actions: vec!["upload".into()],
        },
        PermissionDefinition {
            code: "resource.update".into(),
            name: "Resource Update".into(),
            description: "Update protected resources.".into(),
            category: "resource".into(),
            resource_type: "resource".into(),
            actions: vec!["update".into()],
        },
        PermissionDefinition {
            code: "resource.delete".into(),
            name: "Resource Delete".into(),
            description: "Delete protected resources.".into(),
            category: "resource".into(),
            resource_type: "resource".into(),
            actions: vec!["delete".into()],
        },
        PermissionDefinition {
            code: "resource.publish".into(),
            name: "Resource Publish".into(),
            description: "Publish project resources to the workspace catalog.".into(),
            category: "resource".into(),
            resource_type: "resource".into(),
            actions: vec!["publish".into()],
        },
        PermissionDefinition {
            code: "resource.export".into(),
            name: "Resource Export".into(),
            description: "Export protected resources.".into(),
            category: "resource".into(),
            resource_type: "resource".into(),
            actions: vec!["export".into()],
        },
        PermissionDefinition {
            code: "resource.grant".into(),
            name: "Resource Grant".into(),
            description: "Manage resource authorization.".into(),
            category: "resource".into(),
            resource_type: "resource".into(),
            actions: vec!["grant".into()],
        },
        PermissionDefinition {
            code: "knowledge.view".into(),
            name: "Knowledge View".into(),
            description: "View protected knowledge entries.".into(),
            category: "resource".into(),
            resource_type: "knowledge".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "knowledge.create".into(),
            name: "Knowledge Create".into(),
            description: "Create protected knowledge entries.".into(),
            category: "resource".into(),
            resource_type: "knowledge".into(),
            actions: vec!["create".into()],
        },
        PermissionDefinition {
            code: "knowledge.edit".into(),
            name: "Knowledge Edit".into(),
            description: "Edit protected knowledge entries.".into(),
            category: "resource".into(),
            resource_type: "knowledge".into(),
            actions: vec!["edit".into()],
        },
        PermissionDefinition {
            code: "knowledge.publish".into(),
            name: "Knowledge Publish".into(),
            description: "Publish protected knowledge entries.".into(),
            category: "resource".into(),
            resource_type: "knowledge".into(),
            actions: vec!["publish".into()],
        },
        PermissionDefinition {
            code: "knowledge.delete".into(),
            name: "Knowledge Delete".into(),
            description: "Delete protected knowledge entries.".into(),
            category: "resource".into(),
            resource_type: "knowledge".into(),
            actions: vec!["delete".into()],
        },
        PermissionDefinition {
            code: "knowledge.retrieve".into(),
            name: "Knowledge Retrieve".into(),
            description: "Retrieve and use protected knowledge.".into(),
            category: "resource".into(),
            resource_type: "knowledge".into(),
            actions: vec!["retrieve".into()],
        },
        PermissionDefinition {
            code: "knowledge.grant".into(),
            name: "Knowledge Grant".into(),
            description: "Manage knowledge authorization.".into(),
            category: "resource".into(),
            resource_type: "knowledge".into(),
            actions: vec!["grant".into()],
        },
        PermissionDefinition {
            code: "tool.catalog.view".into(),
            name: "Tool Catalog View".into(),
            description: "Read the shared tool catalog and model catalog.".into(),
            category: "resource".into(),
            resource_type: "tool.catalog".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "tool.catalog.manage".into(),
            name: "Tool Catalog Manage".into(),
            description: "Manage shared tool catalog visibility and configuration.".into(),
            category: "resource".into(),
            resource_type: "tool.catalog".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "provider-credential.view".into(),
            name: "Provider Credential View".into(),
            description: "Read provider credential bindings.".into(),
            category: "resource".into(),
            resource_type: "provider-credential".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "provider-credential.manage".into(),
            name: "Provider Credential Manage".into(),
            description: "Manage provider credential bindings.".into(),
            category: "resource".into(),
            resource_type: "provider-credential".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "tool.builtin.view".into(),
            name: "Builtin Tool View".into(),
            description: "View builtin tools.".into(),
            category: "resource".into(),
            resource_type: "tool.builtin".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "tool.builtin.enable".into(),
            name: "Builtin Tool Enable".into(),
            description: "Enable builtin tools.".into(),
            category: "resource".into(),
            resource_type: "tool.builtin".into(),
            actions: vec!["enable".into()],
        },
        PermissionDefinition {
            code: "tool.builtin.configure".into(),
            name: "Builtin Tool Configure".into(),
            description: "Create and update builtin tool records.".into(),
            category: "resource".into(),
            resource_type: "tool.builtin".into(),
            actions: vec!["configure".into()],
        },
        PermissionDefinition {
            code: "tool.builtin.delete".into(),
            name: "Builtin Tool Delete".into(),
            description: "Delete builtin tool records.".into(),
            category: "resource".into(),
            resource_type: "tool.builtin".into(),
            actions: vec!["delete".into()],
        },
        PermissionDefinition {
            code: "tool.builtin.invoke".into(),
            name: "Builtin Tool Invoke".into(),
            description: "Invoke builtin tools.".into(),
            category: "resource".into(),
            resource_type: "tool.builtin".into(),
            actions: vec!["invoke".into()],
        },
        PermissionDefinition {
            code: "tool.builtin.grant".into(),
            name: "Builtin Tool Grant".into(),
            description: "Manage builtin tool authorization.".into(),
            category: "resource".into(),
            resource_type: "tool.builtin".into(),
            actions: vec!["grant".into()],
        },
        PermissionDefinition {
            code: "tool.skill.view".into(),
            name: "Skill Tool View".into(),
            description: "View managed skill tools.".into(),
            category: "resource".into(),
            resource_type: "tool.skill".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "tool.skill.enable".into(),
            name: "Skill Tool Enable".into(),
            description: "Enable managed skill tools.".into(),
            category: "resource".into(),
            resource_type: "tool.skill".into(),
            actions: vec!["enable".into()],
        },
        PermissionDefinition {
            code: "tool.skill.configure".into(),
            name: "Skill Tool Configure".into(),
            description: "Create and update managed skill tools.".into(),
            category: "resource".into(),
            resource_type: "tool.skill".into(),
            actions: vec!["configure".into()],
        },
        PermissionDefinition {
            code: "tool.skill.publish".into(),
            name: "Skill Tool Publish".into(),
            description: "Publish managed skill tools.".into(),
            category: "resource".into(),
            resource_type: "tool.skill".into(),
            actions: vec!["publish".into()],
        },
        PermissionDefinition {
            code: "tool.skill.delete".into(),
            name: "Skill Tool Delete".into(),
            description: "Delete managed skill tools.".into(),
            category: "resource".into(),
            resource_type: "tool.skill".into(),
            actions: vec!["delete".into()],
        },
        PermissionDefinition {
            code: "tool.skill.invoke".into(),
            name: "Skill Tool Invoke".into(),
            description: "Invoke skill tools.".into(),
            category: "resource".into(),
            resource_type: "tool.skill".into(),
            actions: vec!["invoke".into()],
        },
        PermissionDefinition {
            code: "tool.skill.grant".into(),
            name: "Skill Tool Grant".into(),
            description: "Manage skill tool authorization.".into(),
            category: "resource".into(),
            resource_type: "tool.skill".into(),
            actions: vec!["grant".into()],
        },
        PermissionDefinition {
            code: "tool.mcp.view".into(),
            name: "MCP Tool View".into(),
            description: "View managed MCP tools.".into(),
            category: "resource".into(),
            resource_type: "tool.mcp".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "tool.mcp.enable".into(),
            name: "MCP Tool Enable".into(),
            description: "Enable managed MCP tools.".into(),
            category: "resource".into(),
            resource_type: "tool.mcp".into(),
            actions: vec!["enable".into()],
        },
        PermissionDefinition {
            code: "tool.mcp.configure".into(),
            name: "MCP Tool Configure".into(),
            description: "Create and update managed MCP tools.".into(),
            category: "resource".into(),
            resource_type: "tool.mcp".into(),
            actions: vec!["configure".into()],
        },
        PermissionDefinition {
            code: "tool.mcp.delete".into(),
            name: "MCP Tool Delete".into(),
            description: "Delete managed MCP tools.".into(),
            category: "resource".into(),
            resource_type: "tool.mcp".into(),
            actions: vec!["delete".into()],
        },
        PermissionDefinition {
            code: "tool.mcp.invoke".into(),
            name: "MCP Tool Invoke".into(),
            description: "Invoke MCP tools.".into(),
            category: "resource".into(),
            resource_type: "tool.mcp".into(),
            actions: vec!["invoke".into()],
        },
        PermissionDefinition {
            code: "tool.mcp.bind-credential".into(),
            name: "MCP Tool Bind Credential".into(),
            description: "Bind credentials for MCP tools.".into(),
            category: "resource".into(),
            resource_type: "tool.mcp".into(),
            actions: vec!["bind-credential".into()],
        },
        PermissionDefinition {
            code: "tool.mcp.publish".into(),
            name: "MCP Tool Publish".into(),
            description: "Publish managed MCP tools.".into(),
            category: "resource".into(),
            resource_type: "tool.mcp".into(),
            actions: vec!["publish".into()],
        },
        PermissionDefinition {
            code: "tool.mcp.grant".into(),
            name: "MCP Tool Grant".into(),
            description: "Manage MCP tool authorization.".into(),
            category: "resource".into(),
            resource_type: "tool.mcp".into(),
            actions: vec!["grant".into()],
        },
        PermissionDefinition {
            code: "pet.view".into(),
            name: "Pet View".into(),
            description: "View the workspace pet experience.".into(),
            category: "resource".into(),
            resource_type: "pet".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "pet.manage".into(),
            name: "Pet Manage".into(),
            description: "Manage pet presence and bindings.".into(),
            category: "resource".into(),
            resource_type: "pet".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "artifact.view".into(),
            name: "Artifact View".into(),
            description: "View workspace artifacts.".into(),
            category: "resource".into(),
            resource_type: "artifact".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "inbox.view".into(),
            name: "Inbox View".into(),
            description: "View workspace inbox items.".into(),
            category: "resource".into(),
            resource_type: "inbox".into(),
            actions: vec!["view".into()],
        },
        PermissionDefinition {
            code: "runtime.config.workspace.read".into(),
            name: "Runtime Workspace Config Read".into(),
            description: "Read workspace runtime configuration.".into(),
            category: "runtime".into(),
            resource_type: "runtime.config.workspace".into(),
            actions: vec!["read".into()],
        },
        PermissionDefinition {
            code: "runtime.config.workspace.manage".into(),
            name: "Runtime Workspace Config Manage".into(),
            description: "Validate and save workspace runtime configuration.".into(),
            category: "runtime".into(),
            resource_type: "runtime.config.workspace".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "runtime.config.project.read".into(),
            name: "Runtime Project Config Read".into(),
            description: "Read project runtime configuration.".into(),
            category: "runtime".into(),
            resource_type: "runtime.config.project".into(),
            actions: vec!["read".into()],
        },
        PermissionDefinition {
            code: "runtime.config.project.manage".into(),
            name: "Runtime Project Config Manage".into(),
            description: "Validate and save project runtime configuration.".into(),
            category: "runtime".into(),
            resource_type: "runtime.config.project".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "runtime.config.user.read".into(),
            name: "Runtime User Config Read".into(),
            description: "Read user runtime configuration.".into(),
            category: "runtime".into(),
            resource_type: "runtime.config.user".into(),
            actions: vec!["read".into()],
        },
        PermissionDefinition {
            code: "runtime.config.user.manage".into(),
            name: "Runtime User Config Manage".into(),
            description: "Validate and save user runtime configuration.".into(),
            category: "runtime".into(),
            resource_type: "runtime.config.user".into(),
            actions: vec!["manage".into()],
        },
        PermissionDefinition {
            code: "runtime.session.read".into(),
            name: "Runtime Session Read".into(),
            description: "Read runtime session state, events, and outputs.".into(),
            category: "runtime".into(),
            resource_type: "runtime.session".into(),
            actions: vec!["read".into()],
        },
        PermissionDefinition {
            code: "runtime.submit_turn".into(),
            name: "Runtime Submit Turn".into(),
            description: "Submit new turns to a runtime session.".into(),
            category: "runtime".into(),
            resource_type: "runtime".into(),
            actions: vec!["submit_turn".into()],
        },
        PermissionDefinition {
            code: "runtime.approval.resolve".into(),
            name: "Runtime Approval Resolve".into(),
            description: "Resolve runtime approvals.".into(),
            category: "runtime".into(),
            resource_type: "runtime.approval".into(),
            actions: vec!["resolve".into()],
        },
        PermissionDefinition {
            code: "runtime.auth.resolve".into(),
            name: "Runtime Auth Resolve".into(),
            description: "Resolve runtime auth challenges.".into(),
            category: "runtime".into(),
            resource_type: "runtime.auth".into(),
            actions: vec!["resolve".into()],
        },
        PermissionDefinition {
            code: "runtime.subrun.cancel".into(),
            name: "Runtime Subrun Cancel".into(),
            description: "Cancel runtime subruns by subrun id.".into(),
            category: "runtime".into(),
            resource_type: "runtime.subrun".into(),
            actions: vec!["cancel".into()],
        },
        PermissionDefinition {
            code: "audit.read".into(),
            name: "Audit Read".into(),
            description: "Read workspace audit events.".into(),
            category: "runtime".into(),
            resource_type: "audit".into(),
            actions: vec!["read".into()],
        },
    ]
}


pub(crate) async fn list_access_permission_definitions(
    State(state): State<ServerState>,
    headers: HeaderMap,
) -> Result<Json<Vec<PermissionDefinition>>, ApiError> {
    ensure_authorized_session(&state, &headers, "access.policies.read", None).await?;
    Ok(Json(default_permission_definitions()))
}
