export type DesktopLocale = "en-US" | "zh-CN";

export type MessageKey = keyof typeof messages["en-US"];

const messages = {
  "en-US": {
    "common.english": "English",
    "common.chinese": "中文",
    "common.followSystem": "Follow system",
    "common.light": "Light",
    "common.dark": "Dark",
    "common.system": "System",
    "common.open": "Open",
    "common.empty": "Nothing to show yet.",
    "nav.dashboard": "Dashboard",
    "nav.conversation": "Conversation",
    "nav.runs": "Runs",
    "nav.inbox": "Inbox",
    "nav.knowledge": "Knowledge",
    "nav.projects": "Projects",
    "nav.connections": "Connections",
    "nav.models": "Models",
    "nav.preferences": "Preferences",
    "nav.tasks": "Advanced Tasks",
    "shell.brand": "Octopus Control Room",
    "shell.context": "Context",
    "shell.mode": "Mode",
    "shell.connection": "Connection",
    "shell.auth": "Auth",
    "shell.locale": "Language",
    "shell.theme": "Theme",
    "shell.reminders": "Reminders",
    "shell.primary": "Primary",
    "shell.tools": "Tools",
    "shell.runtime": "Runtime",
    "shell.noReminders": "No reminders need attention right now.",
    "shell.readOnly": "Read-only",
    "shell.degraded": "Degraded",
    "shell.workspaceFallback": "Workspace",
    "shell.projectFallback": "Project selection",
    "dashboard.title": "Operational Dashboard",
    "dashboard.subtitle":
      "Resume context, surface system truth, and start work through stable mental models.",
    "dashboard.heroTitle": "Start with intent, not object setup.",
    "dashboard.heroSubtitle":
      "Describe the outcome you want and let the system shape the execution path behind the scenes.",
    "dashboard.promptPlaceholder":
      "Describe the outcome, revision, or next step you need...",
    "dashboard.startConversation": "Start conversation",
    "dashboard.continuePrevious": "Continue previous work",
    "dashboard.continueWork": "Continue work",
    "dashboard.recentConversations": "Recent conversations",
    "dashboard.recentRuns": "Runs needing attention",
    "dashboard.pendingItems": "Pending approvals",
    "dashboard.systemSummary": "System summary",
    "dashboard.risks": "Risks and reminders",
    "dashboard.summaryRuns": "In-progress or failed runs",
    "dashboard.summaryApprovals": "Pending approvals",
    "dashboard.summaryKnowledge": "Visible knowledge updates",
    "dashboard.summaryNotifications": "Reminder signals",
    "dashboard.emptyConversations":
      "No conversation context has been started for this project yet.",
    "dashboard.emptyRuns": "No runs need attention right now.",
    "dashboard.emptyInbox": "No approvals are waiting right now.",
    "dashboard.whyConversationReady": "Proposal ready for confirmation.",
    "dashboard.whyConversationFollowUp": "Follow-up changed the scope and needs review.",
    "dashboard.whyConversationExecution": "Linked to a formal run and ready to resume.",
    "dashboard.whyRunFailed": "Failed run with follow-up needed.",
    "dashboard.whyRunWaiting": "Waiting on approval or recovery.",
    "dashboard.whyRunRunning": "Still running and worth monitoring.",
    "dashboard.whyInbox": "Action is required before execution can continue.",
    "conversation.title": "Governed Conversation",
    "conversation.subtitle":
      "Clarify the goal, shape the proposal, and confirm explicitly before anything runs.",
    "conversation.placeholder":
      "Describe the outcome, constraints, or follow-up you need...",
    "conversation.send": "Send",
    "conversation.empty":
      "Start with the outcome you want to reach. The proposal stays editable until you confirm execution.",
    "conversation.systemIntro":
      "Start by describing the outcome you want. The system will turn it into an execution proposal before anything runs.",
    "conversation.roleUser": "You",
    "conversation.roleSystem": "System",
    "conversation.systemNeedResult":
      "The proposal has a goal. Add scope, constraints, or expected output if you need tighter execution control.",
    "conversation.systemProposalReady":
      "The proposal is ready for review. Confirm when the scope looks right.",
    "conversation.systemFollowUp":
      "This follow-up changes the scope. Review the proposal again before continuing.",
    "conversation.stage": "Stage",
    "conversation.proposal": "Execution Proposal",
    "conversation.goal": "Current goal",
    "conversation.constraints": "Scope and constraints",
    "conversation.expected": "Expected result",
    "conversation.mode": "Execution mode",
    "conversation.risks": "Risk notes",
    "conversation.readiness": "Execution readiness",
    "conversation.readinessDrafting": "Still drafting",
    "conversation.readinessReady": "Ready to confirm",
    "conversation.readinessReconfirm": "Needs reconfirmation",
    "conversation.executionNow": "Run now",
    "conversation.executionScheduled": "Schedule later",
    "conversation.executionEvent": "Event-driven",
    "conversation.confirm": "Confirm and Execute",
    "conversation.openAdvanced": "Open Advanced Tasks",
    "conversation.linkedRun": "Linked run",
    "preferences.title": "Preferences",
    "preferences.subtitle":
      "Language and theme stay global, while user-authored content remains untouched.",
    "preferences.locale": "Language",
    "preferences.theme": "Theme mode",
    "preferences.currentTheme": "Resolved theme: {theme}",
    "preferences.systemLocale": "System locale default applies on first launch.",
    "projects.title": "Projects",
    "projects.subtitle":
      "Pick a project to enter the dashboard and continue work with stable context.",
    "projects.openDashboard": "Open dashboard",
    "projects.empty": "No tracked projects are available in this workspace yet.",
    "runs.title": "Runs",
    "runs.subtitle":
      "Project execution history ranked by what needs attention now, not just raw creation order.",
    "runs.empty": "No runs have been recorded for this project yet.",
    "run.title": "Run Detail",
    "run.subtitle":
      "Result, governance, and diagnosis stay authoritative here after execution starts.",
    "run.conclusion": "Conclusion",
    "run.result": "Result",
    "run.governance": "Governance",
    "run.diagnosis": "Diagnosis",
    "inbox.title": "Approval Inbox",
    "inbox.subtitle":
      "Actions that can unblock governed work stay separate from passive reminders.",
    "inbox.empty": "No approval requests are waiting.",
    "notifications.title": "Reminder Center",
    "notifications.subtitle":
      "Reminder signals stay lighter than inbox actions and remain read-focused.",
    "notifications.empty": "No notifications are pending.",
    "knowledge.title": "Project Knowledge",
    "knowledge.subtitle":
      "Meaning, provenance, trust, and traceability come before internal identifiers.",
    "knowledge.empty": "No shared knowledge entries are visible for this project yet.",
    "connections.title": "Connections",
    "connections.subtitle":
      "Hub mode, auth, session health, and connector visibility remain authoritative here.",
    "models.title": "Models",
    "models.subtitle":
      "Workspace model governance remains visible as a secondary read-focused surface.",
    "tasks.title": "Advanced Tasks",
    "tasks.subtitle":
      "Use direct execution only when you already know exactly what should run.",
    "tasks.recommended":
      "Conversation is the recommended entry path for most work. This surface stays for expert direct execution and automation setup."
  },
  "zh-CN": {
    "common.english": "English",
    "common.chinese": "中文",
    "common.followSystem": "跟随系统",
    "common.light": "浅色",
    "common.dark": "深色",
    "common.system": "系统",
    "common.open": "打开",
    "common.empty": "暂时没有内容。",
    "nav.dashboard": "控制台",
    "nav.conversation": "对话",
    "nav.runs": "运行",
    "nav.inbox": "收件箱",
    "nav.knowledge": "知识",
    "nav.projects": "项目",
    "nav.connections": "连接",
    "nav.models": "模型",
    "nav.preferences": "偏好设置",
    "nav.tasks": "高级任务",
    "shell.brand": "Octopus 控制台",
    "shell.context": "上下文",
    "shell.mode": "模式",
    "shell.connection": "连接",
    "shell.auth": "认证",
    "shell.locale": "语言",
    "shell.theme": "主题",
    "shell.reminders": "提醒",
    "shell.primary": "主路径",
    "shell.tools": "工具区",
    "shell.runtime": "运行态",
    "shell.noReminders": "当前没有需要处理的提醒。",
    "shell.readOnly": "只读",
    "shell.degraded": "降级",
    "shell.workspaceFallback": "工作区",
    "shell.projectFallback": "项目选择",
    "dashboard.title": "运营控制台",
    "dashboard.subtitle":
      "恢复上下文、呈现系统真相，并用少量稳定心智模型来继续工作。",
    "dashboard.heroTitle": "先表达意图，而不是先配置对象。",
    "dashboard.heroSubtitle":
      "描述你想得到的结果，系统会在内部整理执行路径，而不是先把复杂结构抛给你。",
    "dashboard.promptPlaceholder":
      "描述你要达成的结果、需要修改的内容，或下一步想推进的事情……",
    "dashboard.startConversation": "开始对话",
    "dashboard.continuePrevious": "继续上次工作",
    "dashboard.continueWork": "继续工作",
    "dashboard.recentConversations": "最近对话",
    "dashboard.recentRuns": "需要关注的运行",
    "dashboard.pendingItems": "待处理审批",
    "dashboard.systemSummary": "系统摘要",
    "dashboard.risks": "风险与提醒",
    "dashboard.summaryRuns": "进行中或失败的运行",
    "dashboard.summaryApprovals": "待审批事项",
    "dashboard.summaryKnowledge": "最新知识更新",
    "dashboard.summaryNotifications": "提醒信号",
    "dashboard.emptyConversations": "这个项目还没有开始任何对话上下文。",
    "dashboard.emptyRuns": "当前没有需要关注的运行。",
    "dashboard.emptyInbox": "当前没有待审批事项。",
    "dashboard.whyConversationReady": "提案已可确认执行。",
    "dashboard.whyConversationFollowUp": "跟进修改了范围，需要重新确认。",
    "dashboard.whyConversationExecution": "已关联正式运行，可继续推进。",
    "dashboard.whyRunFailed": "运行失败，需要继续处理。",
    "dashboard.whyRunWaiting": "正在等待审批或恢复。",
    "dashboard.whyRunRunning": "仍在运行，值得继续关注。",
    "dashboard.whyInbox": "执行继续前需要你的动作。",
    "conversation.title": "受治理对话",
    "conversation.subtitle":
      "先澄清目标，再形成执行提案，只有显式确认后才会进入正式执行。",
    "conversation.placeholder": "描述目标、约束或你要补充的修改……",
    "conversation.send": "发送",
    "conversation.empty":
      "先从你想达成的结果开始。确认前，提案始终可以修改。",
    "conversation.systemIntro":
      "先描述你想达成的结果。系统会先整理执行提案，确认前不会创建正式运行。",
    "conversation.roleUser": "你",
    "conversation.roleSystem": "系统",
    "conversation.systemNeedResult":
      "目标已经有了。如果你需要更精确的执行，请补充范围、约束或期望结果。",
    "conversation.systemProposalReady": "提案已可审阅，范围确认无误后再执行。",
    "conversation.systemFollowUp":
      "这次跟进改变了范围，请重新检查提案后再继续。",
    "conversation.stage": "阶段",
    "conversation.proposal": "执行提案",
    "conversation.goal": "当前目标",
    "conversation.constraints": "范围与约束",
    "conversation.expected": "期望结果",
    "conversation.mode": "执行方式",
    "conversation.risks": "风险提示",
    "conversation.readiness": "执行就绪度",
    "conversation.readinessDrafting": "仍在草拟",
    "conversation.readinessReady": "可确认执行",
    "conversation.readinessReconfirm": "需要重新确认",
    "conversation.executionNow": "立即执行",
    "conversation.executionScheduled": "稍后调度",
    "conversation.executionEvent": "事件驱动",
    "conversation.confirm": "确认并执行",
    "conversation.openAdvanced": "打开高级任务",
    "conversation.linkedRun": "关联运行",
    "preferences.title": "偏好设置",
    "preferences.subtitle":
      "语言和主题是全局偏好；用户自己写的内容保持原样，不会被自动翻译。",
    "preferences.locale": "语言",
    "preferences.theme": "主题模式",
    "preferences.currentTheme": "当前解析主题：{theme}",
    "preferences.systemLocale": "首次启动默认跟随系统语言。",
    "projects.title": "项目",
    "projects.subtitle":
      "选择一个项目进入控制台，在稳定上下文里继续工作。",
    "projects.openDashboard": "进入控制台",
    "projects.empty": "当前工作区还没有可用项目。",
    "runs.title": "运行",
    "runs.subtitle": "按“现在最需要关注什么”排序，而不是只按对象罗列。",
    "runs.empty": "这个项目还没有任何运行记录。",
    "run.title": "运行详情",
    "run.subtitle": "执行开始后，结果、治理与诊断都以这里为准。",
    "run.conclusion": "结论",
    "run.result": "结果",
    "run.governance": "治理",
    "run.diagnosis": "诊断",
    "inbox.title": "审批收件箱",
    "inbox.subtitle": "能推动系统继续运行的动作必须与普通提醒分开。",
    "inbox.empty": "当前没有待审批请求。",
    "notifications.title": "提醒中心",
    "notifications.subtitle": "提醒比收件箱更轻，只负责提示，不承担动作权威。",
    "notifications.empty": "当前没有提醒。",
    "knowledge.title": "项目知识",
    "knowledge.subtitle": "先看意义、来源、信任与可追踪性，再看内部标识。",
    "knowledge.empty": "这个项目当前还没有可见的共享知识条目。",
    "connections.title": "连接",
    "connections.subtitle": "这里仍然是 Hub 模式、认证、会话与连接可见性的权威页面。",
    "models.title": "模型",
    "models.subtitle": "工作区模型治理继续作为次级只读页面存在。",
    "tasks.title": "高级任务",
    "tasks.subtitle": "仅当你已经明确知道要执行什么时，再直接使用这里。",
    "tasks.recommended": "大多数工作建议从对话进入；这里保留给高级直接执行与自动化设置。"
  }
} as const;

export function translate(
  locale: DesktopLocale,
  key: MessageKey,
  params: Record<string, string | number> = {}
): string {
  let template = String(messages[locale][key] ?? key);

  for (const [paramKey, value] of Object.entries(params)) {
    template = template.replaceAll(`{${paramKey}}`, String(value));
  }

  return template;
}
